version: "3.2"

services:
  dev:
    container_name: node-bittensor
    image: "ghcr.io/jupiterapex1/bittensor:latest"
    ports:
      - "8091:8091"

    command: /bin/bash -c "
      cd /bittensor
      && bittensor-cli new_coldkey --wallet.name test --no_password
      && bittensor-cli new_hotkey --wallet.name test --wallet.hotkey test --no_password
      && python3.7 miners/gpt2_genesis.py --subtensor.network kusanagi --wallet.name test --wallet.hotkey test"
